export const adminRouteOrder = [
  'dashboard',
  'orders',
  'ordersWorkspace',
  'settlements',
  'financeWorkspace',
  'support',
  'supportWorkspace',
  'vendors',
  'vendorWorkspace',
  'vendorOnboarding',
  'vendorOnboardingWorkspace',
  'products',
  'productWorkspace',
  'categoryWorkspace',
  'productTypeWorkspace',
  'pageBuilder',
  'pageBuilderWorkspace',
  'settings',
  'smsSettingsWorkspace',
  'storefrontInfoPagesWorkspace',
  'paymentGatewayWorkspace',
  'pushNotificationWorkspace',
  'content',
  'contentWorkspace',
  'alerts',
  'accessControl',
  'accessControlWorkspace',
] as const

export type AdminRoute = (typeof adminRouteOrder)[number]

export const adminRouteLabels: Record<AdminRoute, string> = {
  dashboard: 'داشبورد',
  orders: 'سفارش ها',
  ordersWorkspace: 'میزکار سفارش',
  settlements: 'تسویه و مالی',
  financeWorkspace: 'میزکار مالی',
  support: 'پشتیبانی',
  supportWorkspace: 'میزکار پشتیبانی',
  vendors: 'فروشنده ها و ریسک',
  vendorWorkspace: 'میزکار فروشنده',
  vendorOnboarding: 'درخواست‌های فروشندگی',
  vendorOnboardingWorkspace: 'بررسی درخواست فروشنده',
  products: 'محصولات',
  productWorkspace: 'میزکار محصول',
  categoryWorkspace: 'میزکار دسته‌بندی',
  productTypeWorkspace: 'میزکار نوع محصول',
  pageBuilder: 'صفحه‌ساز استور',
  pageBuilderWorkspace: 'میزکار صفحه‌ساز',
  settings: 'تنظیمات',
  smsSettingsWorkspace: 'تنظیمات پیامک',
  storefrontInfoPagesWorkspace: 'تنظیمات صفحات سایت',
  paymentGatewayWorkspace: 'تنظیمات درگاه پرداخت',
  pushNotificationWorkspace: 'ارسال پوش نوتیفیکیشن',
  content: 'محتوا و سئو',
  contentWorkspace: 'ویرایشگر محتوایی',
  alerts: 'هشدارها و اعلان ها',
  accessControl: 'کاربران و دسترسی',
  accessControlWorkspace: 'میزکار دسترسی',
}
