ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_REFUNDED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "Order"
ADD COLUMN "paymentRefundedAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "settlementReleasedAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "settlementReversedAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;

ALTER TABLE "Payment"
ADD COLUMN "refundedAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
